feat: add newplugin and newapp commands
tiagoalvesdulce/politeiagui pull request #3
Opened 2021-10-15 00:31 UTC by victorgcramos

Improvements for https://github.com/decred/politeiagui/pull/2486

This diff creates a new politeiagui CLI with the pgui command.
- adds the newplugin command to create new plugins
- adds the newapp command to create new app-shells.

## Setup

Installation is pretty simple:
```bash
# navigate to the plugins-structure dir
$ cd plugins-structure

# install the CLI
$ npm install -g .
# or locally
$ cd packages/cli && yarn link
```

How to uninstall `pgui` CLI
```bash
# navigate to the plugins-structure dir
$ cd plugins-structure

# uninstall the CLI
$ npm uninstall -g .
# or locally
$ cd packages/cli && yarn unlink
```

## Creating a new plugin

```bash
$ pgui newplugin ticketvote

Creating a new plugin: ticketvote
Directory: /Users/victorguedes/Documents/decred/politeiagui/plugins-structure/packages/ticketvote

Creating plugin files...
Done!
```

Now, if you navigate to `packages/ticketvote`, you'll have the following
file structure:

```
packages/ticketvote
├── jest.config.js
├── package.json
├── src
│   ├── index.html
│   └── index.js
├── webpack.common.js
├── webpack.dev.js
└── webpack.prod.js
```

Let's take a look under the `package.json`:

```json
{
  "name": "@politeiagui/ticketvote",
  "main": "dist/main.js",
  "version": "1.0.0",
  "module": "src/index.js",
  "license": "MIT",
  "scripts": {
    "prettier": "prettier \"src/**/*.js\"",
    "format": "yarn prettier --write",
    "test:format": "yarn prettier --check",
    "test:eslint": "eslint --ext .js ./src",
    "test:ci": "npm run test:format && npm run test:eslint && cross-env jest --no-cache",
    "test:dev": "npm run test:format && npm run test:eslint && cross-env jest --watchAll --no-cache",
    "test": "is-ci \"test:ci\" \"test:dev\"",
    "test:coverage": "yarn test:ci; open coverage/lcov-report/index.html",
    "build": "webpack --config webpack.prod.js",
    "start": "webpack serve --config webpack.dev.js --open"
  },
  "dependencies": {
    "@politeiagui/core": "1.0.0"
  },
  "devDependencies": {}
}
```

## Creating a new app-shell

```bash
$ pgui newapp proposals
Creating a new app: proposals
Directory: /Users/victorguedes/Documents/decred/politeiagui/plugins-structure/apps/proposals

Creating app files...
Done!
```

Now, if you navigate to `apps/proposals`, you'll have the following
file structure:

```
apps/proposals
├── jest.config.js
├── package.json
├── src
│   ├── index.js
│   └── public
│       └── index.html
├── webpack.common.js
├── webpack.dev.js
└── webpack.prod.js
```

Let's take a look under the `package.json`:

```json
{
  "name": "proposals",
  "version": "1.0.0",
  "main": "dist/main.js",
  "module": "src/index.js",
  "license": "MIT",
  "scripts": {
    "prettier": "prettier \"src/**/*.js\"",
    "format": "yarn prettier --write",
    "test:format": "yarn prettier --check",
    "test:eslint": "eslint --ext .js ./src",
    "test:ci": "npm run test:format && npm run test:eslint && cross-env jest --no-cache",
    "test:dev": "npm run test:format && npm run test:eslint && cross-env jest --watchAll --no-cache",
    "test": "is-ci \"test:ci\" \"test:dev\"",
    "test:coverage": "yarn test:ci; open coverage/lcov-report/index.html",
    "build": "webpack --config webpack.prod.js",
    "bundle-report": "webpack-bundle-analyzer --port 4200 dist/stats.json",
    "start": "webpack serve --config webpack.dev.js --open"
  },
  "dependencies": {
    "@politeiagui/core": "1.0.0"
  },
  "devDependencies": {
    "webpack-bundle-analyzer": "^4.4.2"
  }
}
```

2021-10-18 12:13 UTC, tiagoalvesdulce requested changes
Good job! This is looking promising.

`plugins-structure/bin/app/src/index.js` and `plugins-structure/bin/plugin/src/index.js` are empty. Can you add something to those files? Comments or a dummy hello world should do.

Also, I see you named your directory `bin`. I don't like that because it's a short for binary. So I understand it's a compiled executable code and some editors might create `.bin` folders, which might be confusing. I would like to see those CLI commands as packages that we can publish to npm (remember we are using workspaces + lerna so we can manage those packages quite well). Please take a look at how https://github.com/transitive-bullshit/create-react-library does it.

2021-10-18 12:13 UTC, tiagoalvesdulce commented on plugins-structure/bin/app/jest.config.js
> +};
I changed the `jest.config.js` in my last commit. This is the new one:

```
module.exports = {
  testEnvironment: "jsdom",
  setupFilesAfterEnv: ["jest-extended/all"]
};
```

2021-10-18 12:13 UTC, tiagoalvesdulce commented on plugins-structure/bin/plugin/jest.config.js
> +};
same

2021-10-18 12:13 UTC, tiagoalvesdulce commented on plugins-structure/bin/plugin/webpack.dev.js
> +    port: 3003,
the port should be a flag of the CLI. All the other attributes of this object can be flags too, but the port is necessary because we can't have conflicting ones. Same for the app.

2021-10-18 19:17 UTC, victorgcramos commented on plugins-structure/bin/plugin/webpack.dev.js
> +    port: 3003,
Makes sense, mate! thanks!

2021-10-22 14:19 UTC, tiagoalvesdulce commented
It's looking good. Found a few issues:

1. In the generated `index.js` for a plugin, you import: `import { store } from "@politeiagui/core"` but store is not used.
2. If I run the `yarn start` command the app opens in the browser with an empty page. Would be nice if we add something to that page. Something like: `Hello from <plugin_title>`.

2021-10-25 11:11 UTC, tiagoalvesdulce reviewed
LGTM. Once you finish the tests, can you add a README with installation and how to use instructions?

2021-11-01 14:39 UTC, tiagoalvesdulce approved these changes
LGTM

2021-11-01 14:58 UTC, merged

2021-11-01 14:59 UTC, victorgcramos commented
BANG! 🚀